### ISSUE TITLE
Manage own ponies

### ISSUE THREAD

**Issue by RichardGoerler** [RichardGoerler/ponyspiel#2]
Add checkbox to mark horse as owned. id i added to a file. File is read when a horse is loaded to check or uncheck the "owned" box. Can be used to gather information about own ponies (yet to add)

**Comment by RichardGoerler** [comment]
### Own ponies feature: Timeline
Get list of future events with dates and times. Including birth of foals, ponies reaching 3 years of age

**Comment by RichardGoerler** [comment]
### To get birth date of pregnant mother
`<button class="tooltipover" data-container="body" data-trigger="focus" data-toggle="popover" data-placement="top" data-content="ist trächtig (10.06.2020 - 07:27)"> <i class="hicon-pregnant nav-color-horse" title="ist trächtig (10.06.2020 - 07:27)">`

class = tooltipover 
*and*
data-content contains "trächtig"

**Comment by RichardGoerler** [comment]
Birth date of pregnant mother is now included as "Fohlen" in facts_values.
Own ponies function is now included

**Comment by Hoernchen215** [comment]
STALL-NVRU-9X2N-SS2P-TPNK-3HSD-MLKQ



________________________________
Von: RichardGoerler <notifications@github.com>
Gesendet: Sonntag, 7. Juni 2020 23:07
An: RichardGoerler/ponyspiel <ponyspiel@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [RichardGoerler/ponyspiel] Manage own ponies (#2)


Birth date of pregnant mother is now included as "Fohlen" in facts_values.
Own ponies function is now included
